import { useState } from 'react'
import { exerciseById } from '../data/exercises'
import { getDashboardStats } from '../domain/stats'
import { getExerciseDecision, getReadiness } from '../domain/engine'
import { confidenceLabel, getProgressionRecommendations } from '../domain/learning'
import type { AppState, ProgressionRecommendation } from '../domain/types'

const pretty=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase())

export function ProgressScreen({ state,onProgression,onUndoProgression }: { state: AppState;onProgression?:(recommendation:ProgressionRecommendation,response:'accept'|'keep'|'defer')=>void;onUndoProgression?:(recommendation:ProgressionRecommendation)=>void }) {
  const [historyFilter,setHistoryFilter]=useState('all')
  const stats = getDashboardStats(state)
  const recent = state.history.slice(0, 12)
  const counts = new Map<string, number>()
  state.history.forEach(session => session.completedExerciseIds.forEach(id => counts.set(id, (counts.get(id) ?? 0) + 1)))
  const favourites = [...counts.entries()].sort((a,b) => b[1] - a[1]).slice(0, 5)
  const maxDuration = Math.max(1, ...recent.map(session => session.durationSeconds))
  const readiness=getReadiness(state)
  const coaching=Object.keys(state.exerciseStats).map(id=>({id,...getExerciseDecision(id,state)})).filter(item=>item.action!=='maintain').slice(0,8)
  const recommendations=getProgressionRecommendations(state)
  const ready=recommendations.filter(item=>item.status==='ready')
  const approaching=Object.entries(state.learningModel.exercises).filter(([,entry])=>entry.progressionStatus==='approaching')
  const latestBalance=state.activeSession?.plan.balanceReport??state.history.find(session=>session.balanceReport)?.balanceReport??state.savedPlans.find(plan=>plan.balanceReport)?.balanceReport
  const filteredEvents=state.learningModel.events.filter(item=>historyFilter==='all'||item.type===historyFilter).slice(0,40)
  const routineLearning=Object.values(state.learningModel.routineContexts).sort((a,b)=>Date.parse(b.lastUpdatedAt)-Date.parse(a.lastUpdatedAt))[0]
  const resolveName=(id?:string)=>id?(exerciseById.get(id)?.name??state.customExercises.find(exercise=>exercise.id===id)?.name??id):'Workout'
  return <div className="screen progress-screen">
    <section className="page-intro"><span className="eyebrow">YOUR TRAINING</span><h1>Progress is the work repeated.</h1><p>A practical view of consistency, balance, and what your on-device coach is learning.</p></section>
    <section className="stats-grid"><div className="stat-tile"><strong>{stats.sessions}</strong><span>sessions</span><small>all time</small></div><div className="stat-tile"><strong>{stats.completed}</strong><span>movements</span><small>completed</small></div><div className="stat-tile"><strong>{stats.streak}</strong><span>day streak</span><small>current</small></div></section>
    <section className="panel learning-panel"><div className="section-heading"><div><h2>Learning</h2><small>Stored only on this device</small></div><span>{Object.keys(state.learningModel.exercises).length} movements</span></div><p className="learning-intro">Feedback changes preference and difficulty separately. Safety, equipment, and routine balance always remain hard constraints.{routineLearning?` Routine structure confidence is ${confidenceLabel(routineLearning.evidence).toLowerCase()} from ${routineLearning.evidence} overall ratings.`:''}</p></section>
    <section className="panel"><div className="section-heading"><h2>Progression readiness</h2><span>{ready.length} ready · {approaching.length} approaching</span></div>{ready.map(item=><article className="progression-card" key={item.id}><header><span className={`progression-type ${item.category}`}>{pretty(item.category)}</span><div><strong>{resolveName(item.exerciseId)}</strong><small>{item.title}</small></div></header><ul>{item.evidence.map(reason=><li key={reason}>{reason}</li>)}</ul>{onProgression&&<div className="progression-actions"><button className="primary" onClick={()=>onProgression(item,'accept')}>Accept progression</button><button className="secondary" onClick={()=>onProgression(item,'keep')}>Keep current</button><button className="secondary" onClick={()=>onProgression(item,'defer')}>Not now</button></div>}</article>)}{!ready.length&&<p className="empty">No progression is ready yet. Successful completions and optional exercise feedback build evidence.</p>}{approaching.slice(0,6).map(([id,entry])=><div className="learning-row" key={id}><div><strong>{resolveName(id)}</strong><small>Approaching readiness · {entry.successfulPerformances} successful sessions</small></div><span>{confidenceLabel(entry.evidence)}</span></div>)}{recommendations.filter(item=>item.status!=='ready').map(item=><div className="learning-row" key={item.id}><div><strong>{resolveName(item.exerciseId)}</strong><small>{item.status==='accepted'?'Recently progressed':item.status==='deferred'?'Deferred for now':'Current level retained'} · {item.title}</small></div>{item.status==='accepted'&&onUndoProgression?<button className="secondary compact" onClick={()=>onUndoProgression(item)}>Undo progression</button>:<span>{pretty(item.status)}</span>}</div>)}</section>
    <section className="panel"><div className="section-heading"><h2>Routine balance and recent load</h2><span className={`readiness ${readiness.status}`}>{readiness.status}</span></div><div className="readiness-grid">{readiness.rows.map(row=><div key={row.area} className={`readiness-row ${row.status}`}><strong>{row.area}</strong><span>{row.label}</span><small>{row.load} load</small></div>)}</div>{latestBalance?<div className="balance-summary"><div><strong>Template</strong><span>{pretty(latestBalance.templateKey)}</span></div><div><strong>Required patterns</strong><span>{latestBalance.requiredRoles.map(pretty).join(', ')||'Recovery structure'}</span></div><div><strong>Covered patterns</strong><span>{latestBalance.coveredRoles.map(pretty).join(', ')}</span></div><div><strong>Body-area coverage</strong><span>{latestBalance.requiredAreas.length?latestBalance.requiredAreas.map(pretty).join(', '):'Full-body balance'}</span></div>{latestBalance.issues.length?<div className="balance-issues"><strong>Detected issues</strong><span>{latestBalance.issues.join(' ')}</span></div>:<div><strong>Validation</strong><span>All required coverage and safety checks passed.</span></div>}</div>:<p className="empty">Generate and complete a workout to see its stored balance report.</p>}</section>
    <section className="panel"><div className="section-heading"><h2>Coach recommendations</h2><span>{coaching.length} changes</span></div>{coaching.length?coaching.map(item=><div className="coach-row" key={item.id}><span className={`coach-action ${item.action}`}>{item.action==='progress'?'↑':'↓'}</span><div><strong>{resolveName(item.id)}</strong><small>{item.reason}</small></div></div>):<p className="empty">Rate completed sessions to build coaching evidence.</p>}</section>
    <section className="panel"><div className="section-heading"><h2>Feedback and adjustment history</h2><select aria-label="Filter learning history" value={historyFilter} onChange={event=>setHistoryFilter(event.target.value)}><option value="all">All activity</option><option value="exercise_feedback">Exercise feedback</option><option value="overall_rating">Workout ratings</option><option value="skipped">Skips</option><option value="swapped_out">Swaps</option><option value="easier">Easier choices</option><option value="harder">Harder choices</option><option value="favourited">Favourites</option><option value="avoided">Avoids</option><option value="progression_accepted">Accepted progressions</option><option value="progression_reverted">Reverted progressions</option></select></div>{filteredEvents.map(item=><div className="learning-row" key={item.id}><div><strong>{item.label}</strong><small>{resolveName(item.exerciseId)} · {new Date(item.at).toLocaleDateString()}</small></div><span>{item.exerciseId?confidenceLabel(state.learningModel.exercises[item.exerciseId]?.evidence??0):'Routine'}</span></div>)}{!filteredEvents.length&&<p className="empty">No matching learning activity yet.</p>}</section>
    <section className="panel"><div className="section-heading"><h2>Recent volume</h2><span>12 sessions</span></div><div className="bar-chart">{recent.slice().reverse().map(session => <div className="bar-column" key={session.id}><div style={{ height: `${Math.max(8, session.durationSeconds / maxDuration * 100)}%` }} title={`${Math.round(session.durationSeconds/60)} minutes`}/><small>{new Date(session.date).getDate()}</small></div>)}</div></section>
    <section className="panel"><div className="section-heading"><h2>Most practised</h2></div>{favourites.length ? favourites.map(([id,count], index) => <div className="rank-row" key={id}><span>{index + 1}</span><strong>{resolveName(id)}</strong><small>{count} completions</small></div>) : <p className="empty">Complete your first workout to start building a movement profile.</p>}</section>
    <section className="panel"><div className="section-heading"><h2>Recent sessions</h2></div>{recent.slice(0,6).map(session => <div className="session-row" key={session.id}><span className={`session-dot ${session.intention}`}/><div><strong>{session.planName}</strong><small>{new Date(session.date).toLocaleDateString()} · {Math.round(session.durationSeconds/60)} min</small></div><b>{session.rating === 'good' ? '●' : session.rating === 'easy' ? '○' : session.rating === 'hard' ? '▲' : session.rating==='brutal'?'◆':'–'}</b></div>)}</section>
  </div>
}
